version: '3.1'

services:
  db:
    image: mysql
    container_name: mysqlSD2
    command: --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306"
    volumes:
      - ./CodigoBBDD.sql:/docker-entrypoint-initdb.d/CodigoBBDD.sql